[theme]
primaryColor = "#D50032"  # Cardinal Health's primary red
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#FCE4E4"  # Light red for sidebar background
textColor = "#000000"  # Black text for strong readability
font = "sans serif"  # Professional sans serif font